# core/premium.py
"""
Premium key management for OTP-Bot-Telegram.
Handles generation, storage, redemption, and tracking of premium keys.

Keys are stored in the DATABASE (server-side source of truth). The old
conf/premium_keys.json store is migrated to Postgres once on startup and is
never used for grants afterwards. All functions delegate to core.entitlements.
"""
import logging
from datetime import datetime
from pathlib import Path
from typing import Optional, List, Dict, Any

from core import entitlements

logger = logging.getLogger("OTP-Bot.premium")

# ======================================================================
# Constants
# ======================================================================
# Legacy JSON path exists only for one-time migration into Postgres.
PREMIUM_KEYS_PATH = Path("conf") / "premium_keys.json"
KEY_LENGTH = 12
KEY_CHARS = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"

# ======================================================================
# Key storage operations (DB-backed)
# ======================================================================
def load_premium_keys() -> List[Dict[str, Any]]:
    """Load all premium keys from the database store."""
    return entitlements.load_premium_keys()

def save_premium_keys(keys: List[Dict[str, Any]]) -> None:
    """Legacy shim — the DB is authoritative and generation is atomic there."""
    logger.warning("🛑 save_premium_keys() is obsolete; keys live in the DB now. Write ignored.")

# ======================================================================
# Key generation
# ======================================================================
def generate_premium_key(days: int, created_by: str) -> Dict[str, Any]:
    """
    Generate a new premium key and persist it in the database.
    """
    key = entitlements.generate_premium_key(days, created_by)
    if key is None:
        raise RuntimeError("Database unavailable — could not create premium key")
    logger.info(f"Premium key generated by {created_by}: {key['token']} ({days} days)")
    return key

def generate_multiple_keys(days: int, created_by: str, count: int) -> List[Dict[str, Any]]:
    """Generate multiple premium keys at once."""
    keys = []
    for _ in range(count):
        keys.append(generate_premium_key(days, created_by))
    logger.info(f"Generated {count} premium keys by {created_by}")
    return keys

# ======================================================================
# Key lookup and validation
# ======================================================================
def find_premium_key(token: str) -> Optional[Dict[str, Any]]:
    """Find a premium key by its token (case-insensitive)."""
    return entitlements.find_premium_key(token)

def is_key_used(token: str) -> bool:
    key = entitlements.find_premium_key(token)
    return key is not None and key.get("used", False)

def get_unused_premium_keys() -> List[Dict[str, Any]]:
    return entitlements.get_unused_premium_keys()

def get_used_premium_keys() -> List[Dict[str, Any]]:
    return entitlements.get_used_premium_keys()

# ======================================================================
# Key redemption (atomic database claim)
# ======================================================================
def redeem_premium_key(user_id: str, token: str) -> tuple:
    """Atomically claim a key in the database and apply its grant.

    Returns (success: bool, message: str) where message is either the expiry
    date / calls granted, or an error text. A key can never be double-claimed,
    even under concurrency.
    """
    return entitlements.redeem_premium_key(user_id, token)

# ======================================================================
# Key statistics
# ======================================================================
def get_key_stats() -> Dict[str, Any]:
    return entitlements.get_key_stats()

# ======================================================================
# Key formatting for display
# ======================================================================
def format_key_for_display(key: Dict[str, Any]) -> str:
    status = "✅ Used" if key.get("used") else "🔵 Unused"
    lines = [
        f"<code>{key['token']}</code> — {key['days']} day(s) — {status}",
        f"  Created by: <code>{key.get('created_by', 'Unknown')}</code> at {key.get('created_at', 'Unknown')}",
    ]
    if key.get("used"):
        lines.append(f"  Used by: <code>{key.get('used_by', 'Unknown')}</code> at {key.get('used_at', 'Unknown')}")
    return "\n".join(lines)

def format_key_list(keys: List[Dict[str, Any]], show_used: bool = False) -> str:
    """Format a list of keys for display."""
    if not keys:
        return "No keys found."

    filtered = keys if show_used else [k for k in keys if not k.get("used")]
    if not filtered:
        return "No unused keys found."

    lines = []
    for key in filtered:
        lines.append(format_key_for_display(key))
    return "\n\n".join(lines)

# ======================================================================
# Utility functions (compatibility) — DB-backed
# ======================================================================
def get_purchase_count(user_id: str) -> int:
    """Get purchase count for a user (compatibility function)."""
    return entitlements.get_purchase_count(user_id)

def set_purchase_count(user_id: str, count: int) -> None:
    """Set purchase count for a user (compatibility function)."""
    return entitlements.set_purchase_count(user_id, count)

# ======================================================================
# Example usage (comment out when importing)
# ======================================================================
if __name__ == "__main__":
    key = generate_premium_key(7, "test_admin")
    print(f"Generated key: {key['token']}")
    found = find_premium_key(key['token'])
    print(f"Found: {found is not None}")
    stats = get_key_stats()
    print(f"Stats: {stats}")