# core/premium.py
"""
Premium key management for OTP-Bot-Telegram.
Handles generation, storage, redemption, and tracking of premium keys.
Keys are stored in conf/premium_keys.json with atomic operations.
"""
import os
import secrets
import string
import json
import logging
from datetime import datetime, timedelta
from pathlib import Path
from typing import Optional, List, Dict, Any

from core.files import ensure_user_path, write_user_file, read_user_file
from core.auth import check_subscription
from core.user_manager import set_user_premium, set_user_subscription_end_date

logger = logging.getLogger("OTP-Bot.premium")

# ======================================================================
# Constants
# ======================================================================
PREMIUM_KEYS_PATH = Path("conf") / "premium_keys.json"
KEY_LENGTH = 12
KEY_CHARS = string.ascii_uppercase + string.digits

# ======================================================================
# Key storage operations
# ======================================================================
def load_premium_keys() -> List[Dict[str, Any]]:
    """
    Load all premium keys from the JSON store.
    
    Returns:
        List of key dictionaries, each containing:
            token, days, created_by, created_at, used, used_by, used_at
    """
    if not PREMIUM_KEYS_PATH.exists():
        return []
    
    try:
        with open(PREMIUM_KEYS_PATH, "r", encoding="utf-8") as f:
            return json.load(f)
    except Exception as e:
        logger.error(f"Failed to load premium keys: {e}")
        return []

def save_premium_keys(keys: List[Dict[str, Any]]) -> None:
    """
    Save premium keys to the JSON store atomically.
    
    Args:
        keys: List of key dictionaries
    """
    # Ensure conf directory exists
    PREMIUM_KEYS_PATH.parent.mkdir(parents=True, exist_ok=True)
    
    # Write to temporary file and replace the destination atomically.
    temp_path = PREMIUM_KEYS_PATH.with_suffix(".tmp")
    try:
        with open(temp_path, "w", encoding="utf-8") as f:
            json.dump(keys, f, indent=2)
            f.flush()
        os.replace(temp_path, PREMIUM_KEYS_PATH)
        logger.debug(f"Saved {len(keys)} premium keys")
    except Exception as e:
        logger.error(f"Failed to save premium keys: {e}")
        if temp_path.exists():
            try:
                temp_path.unlink()
            except:
                pass
        raise

# ======================================================================
# Key generation
# ======================================================================
def generate_premium_key(days: int, created_by: str) -> Dict[str, Any]:
    """
    Generate a new premium key.
    
    Args:
        days: Number of days the key grants subscription
        created_by: User ID or username of creator (for audit)
    
    Returns:
        Key dictionary with token, metadata, and timestamps
    """
    token = "".join(secrets.choice(KEY_CHARS) for _ in range(KEY_LENGTH))
    
    key = {
        "token": token,
        "days": int(days),
        "created_by": created_by,
        "created_at": datetime.now().strftime("%d/%m/%Y %H:%M:%S"),
        "used": False,
        "used_by": None,
        "used_at": None,
    }
    
    # Load existing keys, append, save
    keys = load_premium_keys()
    keys.append(key)
    save_premium_keys(keys)
    
    logger.info(f"Premium key generated by {created_by}: {token} ({days} days)")
    return key

def generate_multiple_keys(days: int, created_by: str, count: int) -> List[Dict[str, Any]]:
    """
    Generate multiple premium keys at once.
    
    Args:
        days: Number of days each key grants
        created_by: Creator user ID
        count: Number of keys to generate
    
    Returns:
        List of generated key dictionaries
    """
    keys = []
    for _ in range(count):
        keys.append(generate_premium_key(days, created_by))
    
    logger.info(f"Generated {count} premium keys by {created_by}")
    return keys

# ======================================================================
# Key lookup and validation
# ======================================================================
def find_premium_key(token: str) -> Optional[Dict[str, Any]]:
    """
    Find a premium key by its token.
    
    Args:
        token: Token string (case-insensitive)
    
    Returns:
        Key dictionary if found, None otherwise
    """
    token = token.strip().upper()
    for key in load_premium_keys():
        if key.get("token") == token:
            return key
    return None

def is_key_used(token: str) -> bool:
    """
    Check if a premium key has already been used.
    
    Args:
        token: Token string
    
    Returns:
        True if key is used, False otherwise
    """
    key = find_premium_key(token)
    return key is not None and key.get("used", False)

def get_unused_premium_keys() -> List[Dict[str, Any]]:
    """
    Get all unused premium keys.
    
    Returns:
        List of unused key dictionaries
    """
    return [k for k in load_premium_keys() if not k.get("used")]

def get_used_premium_keys() -> List[Dict[str, Any]]:
    """
    Get all used premium keys.
    
    Returns:
        List of used key dictionaries
    """
    return [k for k in load_premium_keys() if k.get("used")]

# ======================================================================
# Key redemption
# ======================================================================
def redeem_premium_key(user_id: str, token: str) -> tuple:
    """
    Redeem a premium key for a user.
    
    Args:
        user_id: User ID
        token: Token string
    
    Returns:
        (success: bool, message: str) where message is either expiry date or error text
    """
    token = token.strip().upper()
    keys = load_premium_keys()
    
    for key in keys:
        if key.get("token") == token:
            # Check if already used
            if key.get("used", False):
                return False, "This premium key has already been used."
            
            # Get days from key
            days = key.get("days", 0)
            if days <= 0:
                return False, "Invalid premium key configuration."
            
            # Calculate new expiry
            now = datetime.now()
            expiry = now
            
            # If user already has an active subscription, extend from current expiry
            if check_subscription(user_id) == "ACTIVE":
                current_exp = read_user_file(user_id, "subs.txt", "")
                try:
                    current = datetime.strptime(current_exp, "%d/%m/%Y")
                    expiry = max(now, current)
                except:
                    expiry = now
            
            # Add days
            expiry += timedelta(days=days)
            expiry_str = expiry.strftime("%d/%m/%Y")
            
            # ✅ UPDATE FILE (legacy system)
            write_user_file(user_id, "subs.txt", expiry_str)
            logger.info(f"   ✅ Updated file: User {user_id} subscription expires {expiry_str}")
            
            # ✅ UPDATE POSTGRESQL (new system) - persist exact expiry so DB and file match
            try:
                # Mark role as a key-scoped premium so redeemed keys only grant Normal Call access
                db_success = set_user_subscription_end_date(user_id, expiry, role="premium_key")
            except Exception:
                db_success = False

            if db_success:
                logger.info(f"   ✅ Updated PostgreSQL: User {user_id} premium status ACTIVE (expires {expiry_str})")
            else:
                logger.warning(f"   ⚠️  Failed to update PostgreSQL for user {user_id} (key still redeemed in file)")
            
            # Mark key as used (IMMUTABLE - prevents re-use)
            key["used"] = True
            key["used_by"] = user_id
            key["used_at"] = datetime.now().strftime("%d/%m/%Y %H:%M:%S")
            key["redemption_expiry"] = expiry_str  # Lock the expiry date in the key record
            
            # Save updated keys (prevents further manipulation)
            save_premium_keys(keys)
            logger.info(f"✅ KEY REDEEMED: {token}")
            logger.info(f"   User: {user_id}")
            logger.info(f"   Duration: {days} day(s)")
            logger.info(f"   Expires: {expiry_str}")
            logger.info(f"   Key marked USED (cannot be redeemed again)")
            
            # Update purchase count (optional loyalty adjustment)
            current_purchases = get_purchase_count(user_id)
            set_purchase_count(user_id, current_purchases - 5)  # Deduct 5 purchases for key redemption
            
            return True, expiry_str
    
    return False, "Premium key not found. Please check your code and try again."

# ======================================================================
# Key statistics
# ======================================================================
def get_key_stats() -> Dict[str, Any]:
    """
    Get statistics about premium keys.
    
    Returns:
        Dict with keys: total, used, unused, generated_today
    """
    keys = load_premium_keys()
    total = len(keys)
    used = sum(1 for k in keys if k.get("used"))
    unused = total - used
    
    # Count keys generated today
    today = datetime.now().strftime("%d/%m/%Y")
    generated_today = sum(
        1 for k in keys 
        if k.get("created_at", "").startswith(today)
    )
    
    return {
        "total": total,
        "used": used,
        "unused": unused,
        "generated_today": generated_today,
    }

# ======================================================================
# Key formatting for display
# ======================================================================
def format_key_for_display(key: Dict[str, Any]) -> str:
    """
    Format a premium key for display in Telegram.
    
    Args:
        key: Key dictionary
    
    Returns:
        Formatted string with key details
    """
    status = "✅ Used" if key.get("used") else "🔵 Unused"
    lines = [
        f"<code>{key['token']}</code> — {key['days']} day(s) — {status}",
        f"  Created by: <code>{key.get('created_by', 'Unknown')}</code> at {key.get('created_at', 'Unknown')}",
    ]
    if key.get("used"):
        lines.append(f"  Used by: <code>{key.get('used_by', 'Unknown')}</code> at {key.get('used_at', 'Unknown')}")
    return "\n".join(lines)

def format_key_list(keys: List[Dict[str, Any]], show_used: bool = False) -> str:
    """
    Format a list of keys for display.
    
    Args:
        keys: List of key dictionaries
        show_used: Whether to show used keys
    
    Returns:
        Formatted string with all keys
    """
    if not keys:
        return "No keys found."
    
    filtered = keys if show_used else [k for k in keys if not k.get("used")]
    if not filtered:
        return "No unused keys found."
    
    lines = []
    for key in filtered:
        lines.append(format_key_for_display(key))
    return "\n\n".join(lines)

# ======================================================================
# Utility functions (compatibility)
# ======================================================================
def get_purchase_count(user_id: str) -> int:
    """Get purchase count for a user (compatibility function)."""
    try:
        return int(read_user_file(user_id, "purchase_count.txt", "0"))
    except:
        return 0

def set_purchase_count(user_id: str, count: int) -> None:
    """Set purchase count for a user (compatibility function)."""
    write_user_file(user_id, "purchase_count.txt", str(max(0, count)))

# ======================================================================
# Example usage (comment out when importing)
# ======================================================================
if __name__ == "__main__":
    # Test key generation
    key = generate_premium_key(7, "test_admin")
    print(f"Generated key: {key['token']}")
    
    # Test key lookup
    found = find_premium_key(key['token'])
    print(f"Found: {found is not None}")
    
    # Test key stats
    stats = get_key_stats()
    print(f"Stats: {stats}")